stages:
  - build

include:
  - local: ".ci/docker-build.yml"

docker-build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH =~ /^dev\/.*$/
      when: always
    - if: $CI_COMMIT_BRANCH
      when: manual
