[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "comp_dart"
version = "0.1.0"
description = "Deep Potential Agent for atomistic simulation"
readme = "README.md"
requires-python = "==3.12.8"

dependencies = [
    "tqdm",
    "requests>=2.32.3",
    "flask>=3.1.1",
    "scipy>=1.12.0",
    "ase>=3.22.1",
    "seekpath>=2.0.1",
    "torchaudio",
    "torchvision",
    "tensorflow==2.19.0",
    "deepmd-kit==3.1.0",  
    "numpy==1.26.4",
    "dpdata==0.2.25",
    "phonopy",
    "pymatgen",
    "spglib",
    "matplotlib",    
    "typing-extensions",  
    "pyyaml",
    "bohr-agent-sdk>=0.1.101",
    "jsonpickle>=4.1.1",
    "dpdispatcher @ git+https://github.com/zjgemi/dpdispatcher.git@sandbox",
    "bohrium-sdk @ git+https://github.com/zjgemi/bohrium-openapi-python-sdk.git@sandbox-env"
]

[project.optional-dependencies]
dev = [
    "pytest>=6.2.0",
    "black>=21.0.0",
    "flake8>=3.9.0",
]
docs = [
    "sphinx>=4.0.0",
]

[project.scripts]
comp-dart = "comp_dart.server:main"

[tool.setuptools.packages.find]
include = ["comp_dart*", "comp_dart.*"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.cif", "*.pt", "*.pth"]