[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "comp_dart"
version = "0.1.0"
description = "Deep Potential Agent for atomistic simulation"
readme = "README.md"
# [修正1] 必须放宽，适配 Docker 的 Python 3.10
requires-python = ">=3.10"

dependencies = [
    "tqdm",
    "requests>=2.32.3",
    "flask>=3.1.1",
    "scipy>=1.12.0",
    "ase>=3.22.1",
    "seekpath>=2.0.1",
    "torchaudio",
    "torchvision",
    "torch==2.7.0",
    # "deepmd-kit @ git+https://github.com/iProzd/deepmd-kit.git@4cc677d6adf4fa1fd6202fbc6008bbd6bd0fe21f",
    "numpy==1.26.4",
    "dpdata==0.2.25",
    "phonopy",
    "pymatgen",
    "spglib",
    "matplotlib",
    "typing-extensions",
    "pyyaml",
    "bohr-agent-sdk>=0.1.101",
    "jsonpickle>=4.1.1",
    "dpdispatcher @ git+https://github.com/zjgemi/dpdispatcher.git@sandbox",
    "bohrium-sdk @ git+https://github.com/zjgemi/bohrium-openapi-python-sdk.git@sandbox-env"
]

[project.optional-dependencies]
dev = [
    "pytest>=6.2.0",
    "black>=21.0.0",
    "flake8>=3.9.0",
]
docs = [
    "sphinx>=4.0.0",
]

[project.scripts]
comp-dart = "comp_dart.server:main"

[tool.setuptools.packages.find]
include = ["comp_dart*", "comp_dart.*"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.cif", "*.pt", "*.pth"]
"comp_dart" = ["../constant/*.json", "../struct_template/*"]